# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.14.1'

In [4]:
np.__config__

<module 'numpy.__config__' from '/home/maxim/bin/conda3/lib/python3.6/site-packages/numpy/__config__.py'>

In [5]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
z = np.zeros([10])
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [8]:
z.nbytes

z.size
z.itemsize
z.size * z.itemsize

80

10

8

80

In [9]:
import sys
sys.getsizeof(z)

176

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
!python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
a = np.zeros([10])
a[4] = 1.0
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
a[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.arange(9).reshape([3, 3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
x = np.array([1, 2, 0, 0, 4, 0])
x[x != 0]

array([1, 2, 4])

In [18]:
np.where(x != 0)

(array([0, 1, 4]),)

In [19]:
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
np.random.uniform(size=[3, 3, 3])

array([[[0.69562983, 0.0318571 , 0.79142809],
        [0.427266  , 0.48156437, 0.68861197],
        [0.63762557, 0.88740543, 0.13807691]],

       [[0.15215381, 0.30463173, 0.77628706],
        [0.51693357, 0.23576359, 0.0281602 ],
        [0.18087097, 0.34104048, 0.93589008]],

       [[0.85588016, 0.46893819, 0.11591962],
        [0.3983537 , 0.68271728, 0.64063005],
        [0.37812803, 0.15538479, 0.04387719]]])

In [22]:
np.random.normal(size=[3, 3, 3])

array([[[-2.26935815, -1.50585399,  0.34010569],
        [-0.86934905,  1.14875698, -0.60943726],
        [ 1.01499851,  0.21681069, -0.57547108]],

       [[ 1.2352187 ,  1.05080582,  2.45762542],
        [ 0.10393825, -1.60725627,  0.03650746],
        [-1.57065607, -0.92095479, -1.10101999]],

       [[ 1.18994788, -0.94050308, -0.73159471],
        [-0.09557227, -0.95879233, -0.35070019],
        [-0.7703273 , -0.81809559,  0.0643379 ]]])

In [23]:
np.random.randn(3, 3, 3)

array([[[ 1.71028937, -2.13055471, -1.70573842],
        [ 0.25947029, -0.79779911,  0.37707193],
        [ 0.00283584,  0.83216603, -0.84975406]],

       [[ 1.92091833, -0.21244153,  0.07171132],
        [-0.13740276,  0.79113732, -0.74512027],
        [ 1.06025121,  0.04440043,  0.87227684]],

       [[ 1.2261839 ,  0.15537682,  0.17129037],
        [-0.64255059, -1.00152882,  0.62533324],
        [-1.37496336, -1.92229443, -0.26103091]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
r = np.random.normal(size=[10, 10])
np.max(r)
np.min(r)

2.0542832815219008

-2.223726704425178

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
r = np.random.randn(30)
r.mean()
np.mean(r)

-0.043861160803712385

-0.043861160803712385

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
b = np.zeros([5, 5])
b[0,:] = b[-1,:] = b[:,0] = b[:,-1] = 1.0
b

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
c = np.ones([5, 5])
c[1:-1, 1:-1] = 0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
c = np.arange(25).reshape((5, 5))
c

d = np.zeros([7, 7])
d[1:-1, 1:-1] = c
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  9.,  0.],
       [ 0., 10., 11., 12., 13., 14.,  0.],
       [ 0., 15., 16., 17., 18., 19.,  0.],
       [ 0., 20., 21., 22., 23., 24.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
np.pad(c, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [30]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

nan

False

False

nan

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
m = np.zeros([5, 5])
m[np.arange(4) + 1, np.arange(4)] = np.arange(1, 5)
m

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [32]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [33]:
c = np.zeros([8, 8])
c[::2, 1::2] = 1.0
c[1::2, ::2] = 1.0
c

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
a = np.arange(6 * 7 * 8).reshape((6, 7, 8))
v = a.ravel()[100]
v
np.where(a == v)

100

(array([1]), array([5]), array([4]))

In [35]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
np.tile([[1, 0], [0, 1]], (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
r = np.random.randn(5, 5)
(r - r.min()) / (r.max() - r.min())

array([[0.63437923, 0.40801077, 0.42979228, 0.63048507, 0.66596222],
       [0.64152958, 0.        , 0.37867033, 0.4502171 , 0.39213373],
       [0.50781211, 0.0262258 , 0.45549928, 0.10330853, 0.28183643],
       [0.11850169, 0.66268338, 0.67032812, 0.05290053, 0.08025024],
       [0.68814865, 0.6298421 , 1.        , 0.17516886, 0.29980689]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
np.dtype([('R', 'B', 1), ('G', 'B', 1), ('B', 'B', 1), ('A', 'B', 1)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [39]:
a = np.ones([5, 3])
b = np.ones([3, 2])
a.dot(b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
a = np.arange(10)
a[3:9] = -a[3:9]
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [41]:
b = np.arange(10)
mask = b[(3 <= b) & (b <= 8)]
b[mask] = -b[mask]
b

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [42]:
c = np.arange(10)
c[(3 <= c) & (c <= 8)] *= -1
c

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [44]:
sum

<function numpy.core.fromnumeric.sum>

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [45]:
Z = np.arange(4)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([ 1,  1,  4, 27])

array([0, 1, 2, 4])

array([False, False, False, False])

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j])

array([0., 1., 2., 3.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
np.array(0)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array(0)

/home/maxim/bin/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

/home/maxim/bin/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


0

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
a = np.random.uniform(-10,+10,10)
a
np.ceil(np.abs(a))
np.copysign(np.ceil(np.abs(a)), a)

array([ 0.57300407,  8.77258868, -6.80778696, -7.83567587, -4.64947276,
        5.30116523,  5.18862196,  6.66001792,  2.00304495, -7.25616237])

array([1., 9., 7., 8., 5., 6., 6., 7., 3., 8.])

array([ 1.,  9., -7., -8., -5.,  6.,  6.,  7.,  3., -8.])

In [48]:
np.ceil(a)
np.floor(a)

array([ 1.,  9., -6., -7., -4.,  6.,  6.,  7.,  3., -7.])

array([ 0.,  8., -7., -8., -5.,  5.,  5.,  6.,  2., -8.])

#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
a = np.arange(5)
b = np.arange(5) + 2
np.intersect1d(a, b)

array([2, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [50]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [51]:
np.sqrt(-1)
np.emath.sqrt(-1)

nan

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [52]:
np.datetime64('today', 'D') - np.timedelta64(1, 'D')
np.datetime64('today', 'D') + np.timedelta64(1, 'D')

numpy.datetime64('2018-03-19')

numpy.datetime64('2018-03-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [53]:
np.arange('2016-07', '2016-08', dtype=np.datetime64('today', 'D'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [54]:
a = np.ones(5)
b = np.arange(5)
((a + b) * (-a / 2))

array([-0.5, -1. , -1.5, -2. , -2.5])

In [55]:
a = np.ones(5)
b = np.arange(5)
a += b
a *= -(a - b) / 2
a

array([-0.5, -1. , -1.5, -2. , -2.5])

In [56]:
a = np.ones(5, dtype=np.float32)
b = np.arange(5, dtype=np.float32)
np.add(a, b, out=b)
np.multiply(a, -0.5, out=a)
np.multiply(a, b, out=a)

array([1., 2., 3., 4., 5.], dtype=float32)

array([-0.5, -0.5, -0.5, -0.5, -0.5], dtype=float32)

array([-0.5, -1. , -1.5, -2. , -2.5], dtype=float32)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [57]:
r = np.random.uniform(-10, 10, size=(5))
r
r.astype(np.int32)
np.floor(r)
np.ceil(r)
np.round(r)
np.trunc(r)

array([-1.40600216,  7.93717527, -2.76955807, -0.25987544, -6.80488561])

array([-1,  7, -2,  0, -6], dtype=int32)

array([-2.,  7., -3., -1., -7.])

array([-1.,  8., -2., -0., -6.])

array([-1.,  8., -3., -0., -7.])

array([-1.,  7., -2., -0., -6.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [58]:
np.arange(25).reshape([5, 5]) % 5

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [59]:
def gen():
    for i in range(10):
        yield i*i
        
np.array(list(gen()), dtype=np.int32)
np.fromiter(gen(), dtype=np.int32)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [60]:
np.linspace(0, 1, 10, endpoint=False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [61]:
a = np.random.rand(10)
a
np.sort(a)

array([0.31946586, 0.2911352 , 0.76115097, 0.15629624, 0.59643476,
       0.77834913, 0.63607866, 0.52791355, 0.8118612 , 0.003978  ])

array([0.003978  , 0.15629624, 0.2911352 , 0.31946586, 0.52791355,
       0.59643476, 0.63607866, 0.76115097, 0.77834913, 0.8118612 ])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [62]:
a = np.arange(1000)

%timeit np.sum(a)

%timeit np.add.reduce(a, 0)

3.08 µs ± 242 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.88 µs ± 137 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [63]:
a = np.arange(5)
b = np.arange(5)
np.equal(a, b)
np.array_equal(a, b)
np.allclose(a, b)

array([ True,  True,  True,  True,  True])

True

True

#### 43. Make an array immutable (read-only) (★★☆)

In [64]:
a = np.array([1, 2, 3])
a[0] = 2
a

a.flags.writeable=False
a.setflags(write=False)
try:
  a[0] = 3
except BaseException as e:
  print('fail:', e)

array([2, 2, 3])

fail: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [65]:
c = np.random.randn(10, 2)
c

r = np.sqrt(np.sum(c**2, axis=1))
alpha = np.arctan2(c[:, 1], c[:, 0])

r
alpha

array([[-0.92986953,  0.94876297],
       [-0.08094177,  1.68398239],
       [-0.57607919,  0.30789752],
       [ 1.72834339,  0.72149089],
       [ 1.01195807, -0.87668241],
       [-1.35548472,  0.1457581 ],
       [-0.17166579, -0.77391363],
       [-1.31498456,  1.43566378],
       [ 1.03760079, -0.30470387],
       [ 1.53744993, -0.57209906]])

array([1.32846095, 1.68592652, 0.65319837, 1.87289081, 1.33889177,
       1.36329903, 0.79272407, 1.9468731 , 1.08141567, 1.64044189])

array([ 2.34613781,  1.61882505,  2.65075015,  0.3954554 , -0.71389433,
        3.03447219, -1.78907735,  2.3123496 , -0.28563197, -0.35623375])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [66]:
r = np.random.randn(10)
r
r[np.argmax(r)] = 0
r

array([ 0.32330938, -0.34544631, -0.16642647, -0.26939251, -0.08041824,
       -0.10991621, -0.48620972, -1.23132484, -0.28659928,  0.26889409])

array([ 0.        , -0.34544631, -0.16642647, -0.26939251, -0.08041824,
       -0.10991621, -0.48620972, -1.23132484, -0.28659928,  0.26889409])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [67]:
x = y = np.linspace(0, 1, 10)
a, b = np.meshgrid(x, y)
a
b

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.2222222

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.22222222, 0.22222222, 0.22222222, 0.22222222, 0.22222222,
        0.22222222, 0.22222222, 0.22222222, 0.22222222, 0.22222222],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444,
        0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444],
       [0.55555556, 0.55555556, 0.55555556, 0.55555556, 0.55555556,
        0.55555556, 0.55555556, 0.55555556, 0.55555556, 0.55555556],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [0.77777778, 0.77777778, 0.7777777

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [68]:
x = np.arange(10) + 10
y = np.arange(10)
c = np.expand_dims(x, 1) - np.expand_dims(y, 0)
c

np.subtract.outer(x, y)

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2],
       [12, 11, 10,  9,  8,  7,  6,  5,  4,  3],
       [13, 12, 11, 10,  9,  8,  7,  6,  5,  4],
       [14, 13, 12, 11, 10,  9,  8,  7,  6,  5],
       [15, 14, 13, 12, 11, 10,  9,  8,  7,  6],
       [16, 15, 14, 13, 12, 11, 10,  9,  8,  7],
       [17, 16, 15, 14, 13, 12, 11, 10,  9,  8],
       [18, 17, 16, 15, 14, 13, 12, 11, 10,  9],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2],
       [12, 11, 10,  9,  8,  7,  6,  5,  4,  3],
       [13, 12, 11, 10,  9,  8,  7,  6,  5,  4],
       [14, 13, 12, 11, 10,  9,  8,  7,  6,  5],
       [15, 14, 13, 12, 11, 10,  9,  8,  7,  6],
       [16, 15, 14, 13, 12, 11, 10,  9,  8,  7],
       [17, 16, 15, 14, 13, 12, 11, 10,  9,  8],
       [18, 17, 16, 15, 14, 13, 12, 11, 10,  9],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [69]:
np.iinfo(np.int8)
np.iinfo(np.int16)
np.iinfo(np.int32)

iinfo(min=-128, max=127, dtype=int8)

iinfo(min=-32768, max=32767, dtype=int16)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

#### 49. How to print all the values of an array? (★★☆)

In [70]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [71]:
a
b = 1.8
a[np.argmin(np.abs(a - b))]

array([0, 1, 2, 3, 4])

2

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [72]:
a = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
a

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [73]:
a = np.arange(10).reshape((-1, 2))
d = np.expand_dims(a, 1) - np.expand_dims(a, 0)
a
np.sqrt(np.sum(d**2, axis=2))

x, y = np.atleast_2d(a[:,0], a[:,1])
np.sqrt((x-x.T)**2 + (y-y.T)**2)

import scipy.spatial
scipy.spatial.distance.cdist(a, a)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [74]:
x = np.random.rand(5, 5) * 5
x
x.astype(np.int, copy=False)

array([[0.34419687, 2.56458004, 3.10315826, 4.02056037, 3.51700149],
       [3.8064032 , 1.33623141, 0.35672108, 3.35536425, 1.87990268],
       [0.3342677 , 1.85194905, 0.19742938, 0.78574823, 3.91117595],
       [1.06941514, 0.30035246, 2.04998694, 3.83238954, 2.70125869],
       [0.32885993, 1.24708024, 1.56634905, 2.52758611, 1.44988709]])

array([[0, 2, 3, 4, 3],
       [3, 1, 0, 3, 1],
       [0, 1, 0, 0, 3],
       [1, 0, 2, 3, 2],
       [0, 1, 1, 2, 1]])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [75]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
np.genfromtxt(s, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [76]:
x = np.random.randn(2, 2)
for i, val in np.ndenumerate(x):
    print(i, val)
for i in np.ndindex(x.shape):
    print(i)

(0, 0) 0.7990756792736937
(0, 1) -0.9706211678939218
(1, 0) 1.644480473350792
(1, 1) 0.9129409492820459
(0, 0)
(0, 1)
(1, 0)
(1, 1)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [77]:
x, y = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,4))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
np.exp(-((d-mu)**2 / (2.0*sigma**2)))

array([[0.36787944, 0.57375342, 0.57375342, 0.36787944],
       [0.57375342, 0.89483932, 0.89483932, 0.57375342],
       [0.57375342, 0.89483932, 0.89483932, 0.57375342],
       [0.36787944, 0.57375342, 0.57375342, 0.36787944]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [78]:
a = np.zeros([5, 5])
v = np.arange(10) + 1
a.ravel()[np.random.choice(25, 10)] = v
a

array([[ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  4.,  1.,  0.,  0.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  9.],
       [ 0.,  8.,  0.,  5.,  0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [79]:
a = np.random.randn(4, 4)
a
a.mean(axis=1)
a.mean(axis=1, keepdims=True)

array([[-0.76436131,  0.50257796,  0.21603555,  0.76942098],
       [ 1.14305358, -0.29908783,  0.82126435, -0.28518449],
       [-1.1918504 ,  0.67015734, -0.74704909, -1.45098851],
       [ 0.58427768,  0.07902491,  0.89496224,  0.51809198]])

array([ 0.18091829,  0.3450114 , -0.67993267,  0.5190892 ])

array([[ 0.18091829],
       [ 0.3450114 ],
       [-0.67993267],
       [ 0.5190892 ]])

#### 59. How to sort an array by the nth column? (★★☆)

In [80]:
a = np.random.randn(5, 5)
#np.sort(a, axis=1)
a[a[:,2].argsort()]

array([[ 0.65253269,  0.94573071, -1.45755032, -0.0272311 , -0.82253267],
       [ 0.00509897,  0.44059412, -0.30422749,  0.54964687,  0.7337282 ],
       [-1.33623889, -0.77547572, -0.22744872,  0.58728445,  0.23440951],
       [-0.20501179,  1.92945359,  0.23455459, -0.73750097,  0.212184  ],
       [ 0.4896042 ,  0.73729164,  1.35868102, -0.16904799, -0.95545819]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [81]:
b = np.random.randn(3, 6)
b[:, 1] = np.nan
np.logical_and.reduce(np.isnan(b), axis=0)

array([False,  True, False, False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

In [82]:
a
b = 1.8
np.abs(a - b).argmin()
a.flat[np.abs(a - b).argmin()]

# Note: this one fails:
# a[np.abs(a - b).argmin()]

array([[-0.20501179,  1.92945359,  0.23455459, -0.73750097,  0.212184  ],
       [ 0.4896042 ,  0.73729164,  1.35868102, -0.16904799, -0.95545819],
       [ 0.65253269,  0.94573071, -1.45755032, -0.0272311 , -0.82253267],
       [-1.33623889, -0.77547572, -0.22744872,  0.58728445,  0.23440951],
       [ 0.00509897,  0.44059412, -0.30422749,  0.54964687,  0.7337282 ]])

1

1.9294535888749962

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [83]:
x = np.ones([1, 3])
y = np.ones([3, 1]) * 2
x
y
# out = np.zeros([3, 3])

addop = np.add

it = np.nditer([x, y, None], [], [['readonly'], ['readonly'], ['writeonly', 'allocate']])
while not it.finished:
    _ = addop(it[0], it[1], it[2]);
    _ = it.iternext()
    
it.operands[2]

array([[1., 1., 1.]])

array([[2.],
       [2.],
       [2.]])

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

#### 63. Create an array class that has a name attribute (★★☆)

In [84]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', None)

Z = NamedArray(np.arange(10), 'my name')
print (Z.name)
print (Z.info)

my name
None


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [85]:
a = np.arange(5) + 1
a

i = np.array([2, 2, 4, 2])
np.add.at(a, i, 1)
a

array([1, 2, 3, 4, 5])

array([1, 2, 6, 4, 6])

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [86]:
x = np.arange(7) + 1
i = np.array([1, 1, 3, 0, 2, 3, 4])

#np.bincount(i, x)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

In [87]:
w,h = 16,16
image = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)

f = image[...,0] * (256 * 256) + image[...,1] * 256 + image[...,2]
f.shape

np.unique(f).shape

(16, 16)

(8,)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [88]:
x = np.arange(4**4).reshape([4, 4, 4, 4])
x.shape

np.sum(x, axis=(2, 3))

(4, 4, 4, 4)

array([[ 120,  376,  632,  888],
       [1144, 1400, 1656, 1912],
       [2168, 2424, 2680, 2936],
       [3192, 3448, 3704, 3960]])

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [89]:
d = np.arange(8) + 1
s = np.array([1, 2, 0, 2, 1, 2, 1, 1])

sums = np.bincount(s, weights=d)
counts = np.bincount(s)
sums / counts

array([3.  , 5.25, 4.  ])

In [90]:
import pandas as pd
pd.DataFrame(d).groupby(s).mean()

0
0  3.00
1  5.25
2  4.00

#### 69. How to get the diagonal of a dot product? (★★★)

In [91]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 3)
a.dot(b)

np.diag(a.dot(b))

np.einsum("ij,ji->i", a, b)

array([[-0.84337865,  0.07231282,  0.0857814 ],
       [ 0.74075673, -0.08487676, -0.15295434],
       [ 0.86980004, -0.06833858, -0.18255495]])

array([-0.84337865, -0.08487676, -0.18255495])

array([-0.84337865, -0.08487676, -0.18255495])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [92]:
i = np.arange(5) + 1
len = i.shape[0]
n = 3
a = np.zeros(len * (n+1) - n)
a[::4] = i
a

array([1., 0., 0., 0., 2., 0., 0., 0., 3., 0., 0., 0., 4., 0., 0., 0., 5.])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [93]:
a = np.random.randn(5, 5, 3)
b = np.random.randn(5, 5)

e = a * b[:,:,None]
e.shape

(5, 5, 3)

#### 72. How to swap two rows of an array? (★★★)

In [94]:
a = np.arange(16).reshape([4, 4])
a
a[[0,1]] = a[[1, 0]]
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

array([[ 4,  5,  6,  7],
       [ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [95]:
c = np.array([2, 3, 0, 5])

np.repeat(np.arange(c.shape[0]), c)

array([0, 0, 1, 1, 1, 3, 3, 3, 3, 3])

#### 75. How to compute averages using a sliding window over an array? (★★★)

In [96]:
a = np.arange(10)
k = 3
a

b = np.cumsum(a)
b

b[k:] = b[k:] - b[:-k]
b

b = b[k-1:] / k
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])

array([ 0,  1,  3,  6,  9, 12, 15, 18, 21, 24])

array([1., 2., 3., 4., 5., 6., 7., 8.])

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)