# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow and in the numpy documentation. The goal of this collection is to offer a quick reference for both old and new users but also to provide a set of exercices for those who teach.


If you find an error or think you've a better way to solve some of them, feel free to open an issue at <https://github.com/rougier/numpy-100>

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
np.__version__

'1.14.1'

In [4]:
np.__config__

<module 'numpy.__config__' from '/home/maxim/bin/conda3/lib/python3.6/site-packages/numpy/__config__.py'>

In [5]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]


#### 3. Create a null vector of size 10 (★☆☆)

In [6]:
z = np.zeros([10])
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆)

In [7]:
z.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

In [8]:
z.nbytes

z.size
z.itemsize
z.size * z.itemsize

80

10

8

80

In [9]:
import sys
sys.getsizeof(z)

176

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [10]:
print(np.add.__doc__)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

In [11]:
!python -c "import numpy as np; np.info(np.add)"

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [12]:
a = np.zeros([10])
a[4] = 1.0
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)

In [13]:
np.arange(10, 50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [14]:
a

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
a[::-1]

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [16]:
np.arange(9).reshape([3, 3])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)

In [17]:
x = np.array([1, 2, 0, 0, 4, 0])
x[x != 0]

array([1, 2, 4])

In [18]:
np.where(x != 0)

(array([0, 1, 4]),)

In [19]:
np.nonzero(x)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆)

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [21]:
np.random.uniform(size=[3, 3, 3])

array([[[0.44168844, 0.04189614, 0.14043283],
        [0.11707159, 0.93485003, 0.96363274],
        [0.49135178, 0.6471772 , 0.16088294]],

       [[0.78232357, 0.34720151, 0.13093642],
        [0.66757106, 0.65502344, 0.24462713],
        [0.82278685, 0.67198779, 0.41395114]],

       [[0.26586704, 0.23563514, 0.26872451],
        [0.41432078, 0.14315408, 0.51885875],
        [0.0040973 , 0.03914208, 0.76740325]]])

In [22]:
np.random.normal(size=[3, 3, 3])

array([[[ 1.23555335, -0.94909178,  1.05465744],
        [ 0.79779662, -1.27311475, -0.0531153 ],
        [-2.01699069, -0.50654156,  0.83125334]],

       [[-1.47412583, -1.53405305, -0.85715075],
        [-1.72103623,  0.66334492, -0.36340289],
        [-1.13511926,  0.12197554, -0.13984803]],

       [[-0.31460092, -0.87454815,  1.93376394],
        [-0.04495931,  0.06913645,  1.30855825],
        [ 0.60966732,  0.9717363 , -0.08464608]]])

In [23]:
np.random.randn(3, 3, 3)

array([[[-0.36311543,  0.81866138,  1.24537678],
        [ 0.54057184,  0.64055779,  1.76641891],
        [-0.72035591, -0.56632914,  0.63580165]],

       [[ 0.0583561 , -0.15692798, -1.19618875],
        [ 0.38767877, -1.77163414, -0.34441412],
        [-0.07173961, -0.46515955,  0.12882731]],

       [[-1.17090438,  0.36271625, -1.14819304],
        [-0.00227326, -1.52254227,  2.01644252],
        [-0.32022907,  0.5107787 , -0.08598318]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [24]:
r = np.random.normal(size=[10, 10])
np.max(r)
np.min(r)

2.7630828742813844

-2.396873773563766

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [25]:
r = np.random.randn(30)
r.mean()
np.mean(r)

-0.26966855322535893

-0.26966855322535893

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [26]:
b = np.zeros([5, 5])
b[0,:] = b[-1,:] = b[:,0] = b[:,-1] = 1.0
b

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
c = np.ones([5, 5])
c[1:-1, 1:-1] = 0
c

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [28]:
c = np.arange(25).reshape((5, 5))
c

d = np.zeros([7, 7])
d[1:-1, 1:-1] = c
d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

array([[ 0.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  2.,  3.,  4.,  0.],
       [ 0.,  5.,  6.,  7.,  8.,  9.,  0.],
       [ 0., 10., 11., 12., 13., 14.,  0.],
       [ 0., 15., 16., 17., 18., 19.,  0.],
       [ 0., 20., 21., 22., 23., 24.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  0.,  0.]])

In [29]:
np.pad(c, pad_width=1, mode='constant', constant_values=0)

array([[ 0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  1,  2,  3,  4,  0],
       [ 0,  5,  6,  7,  8,  9,  0],
       [ 0, 10, 11, 12, 13, 14,  0],
       [ 0, 15, 16, 17, 18, 19,  0],
       [ 0, 20, 21, 22, 23, 24,  0],
       [ 0,  0,  0,  0,  0,  0,  0]])

#### 17. What is the result of the following expression? (★☆☆)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [30]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

nan

False

False

nan

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [31]:
m = np.zeros([5, 5])
m[np.arange(4) + 1, np.arange(4)] = np.arange(1, 5)
m

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0.],
       [0., 0., 3., 0., 0.],
       [0., 0., 0., 4., 0.]])

In [32]:
np.diag(1 + np.arange(4), k=-1)

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [33]:
c = np.zeros([8, 8])
c[::2, 1::2] = 1.0
c[1::2, ::2] = 1.0
c

array([[0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.],
       [0., 1., 0., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 1., 0., 1., 0.]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [34]:
a = np.arange(6 * 7 * 8).reshape((6, 7, 8))
v = a.ravel()[100]
v
np.where(a == v)

100

(array([1]), array([5]), array([4]))

In [35]:
np.unravel_index(100, (6, 7, 8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [36]:
np.tile([[1, 0], [0, 1]], (4, 4))

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

#### 22. Normalize a 5x5 random matrix (★☆☆)

In [37]:
r = np.random.randn(5, 5)
(r - r.min()) / (r.max() - r.min())

array([[0.32872992, 0.55690775, 0.71441275, 0.95801821, 0.600914  ],
       [0.88536897, 0.53131437, 0.4792759 , 0.97893095, 0.8118921 ],
       [0.76512892, 0.54197053, 1.        , 0.6991727 , 0.86468895],
       [0.9619812 , 0.91366897, 0.89819744, 0.        , 0.6394224 ],
       [0.43471368, 0.43669667, 0.86738132, 0.31132812, 0.93613387]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [38]:
np.dtype([('R', 'B', 1), ('G', 'B', 1), ('B', 'B', 1), ('A', 'B', 1)])

dtype([('R', 'u1'), ('G', 'u1'), ('B', 'u1'), ('A', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [39]:
a = np.ones([5, 3])
b = np.ones([3, 2])
a.dot(b)

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [40]:
a = np.arange(10)
a[3:9] = -a[3:9]
a

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [41]:
b = np.arange(10)
mask = b[(3 <= b) & (b <= 8)]
b[mask] = -b[mask]
b

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

In [42]:
c = np.arange(10)
c[(3 <= c) & (c <= 8)] *= -1
c

array([ 0,  1,  2, -3, -4, -5, -6, -7, -8,  9])

#### 26. What is the output of the following script? (★☆☆)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [43]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


In [44]:
sum

<function numpy.core.fromnumeric.sum>

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [45]:
Z = np.arange(4)
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
# Z<Z>Z

array([ 1,  1,  4, 27])

array([0, 1, 2, 4])

array([False, False, False, False])

array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j])

array([0., 1., 2., 3.])

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [46]:
np.array(0)
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

array(0)

/home/maxim/bin/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


nan

/home/maxim/bin/conda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


0

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆)

In [47]:
a = np.random.uniform(-10,+10,10)
a
np.ceil(np.abs(a))
np.copysign(np.ceil(np.abs(a)), a)

array([ 0.39565854,  4.87743207, -4.97860879, -4.1706611 , -4.65710454,
       -4.52359572, -5.81098106, -7.95726935,  1.07729962, -3.10035946])

array([1., 5., 5., 5., 5., 5., 6., 8., 2., 4.])

array([ 1.,  5., -5., -5., -5., -5., -6., -8.,  2., -4.])

In [48]:
np.ceil(a)
np.floor(a)

array([ 1.,  5., -4., -4., -4., -4., -5., -7.,  2., -3.])

array([ 0.,  4., -5., -5., -5., -5., -6., -8.,  1., -4.])

#### 30. How to find common values between two arrays? (★☆☆)

In [49]:
a = np.arange(5)
b = np.arange(5) + 2
np.intersect1d(a, b)

array([2, 3, 4])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [50]:
np.seterr(all='ignore')

{'divide': 'warn', 'invalid': 'warn', 'over': 'warn', 'under': 'ignore'}

#### 32. Is the following expressions true? (★☆☆)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [51]:
np.sqrt(-1)
np.emath.sqrt(-1)

nan

1j

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [52]:
np.datetime64('today', 'D') - np.timedelta64(1, 'D')
np.datetime64('today', 'D') + np.timedelta64(1, 'D')

numpy.datetime64('2018-03-10')

numpy.datetime64('2018-03-12')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [53]:
np.arange('2016-07', '2016-08', dtype=np.datetime64('today', 'D'))

array(['2016-07-01', '2016-07-02', '2016-07-03', '2016-07-04',
       '2016-07-05', '2016-07-06', '2016-07-07', '2016-07-08',
       '2016-07-09', '2016-07-10', '2016-07-11', '2016-07-12',
       '2016-07-13', '2016-07-14', '2016-07-15', '2016-07-16',
       '2016-07-17', '2016-07-18', '2016-07-19', '2016-07-20',
       '2016-07-21', '2016-07-22', '2016-07-23', '2016-07-24',
       '2016-07-25', '2016-07-26', '2016-07-27', '2016-07-28',
       '2016-07-29', '2016-07-30', '2016-07-31'], dtype='datetime64[D]')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [54]:
a = np.ones(5)
b = np.arange(5)
((a + b) * (-a / 2))

array([-0.5, -1. , -1.5, -2. , -2.5])

In [55]:
a = np.ones(5)
b = np.arange(5)
a += b
a *= -(a - b) / 2
a

array([-0.5, -1. , -1.5, -2. , -2.5])

In [56]:
a = np.ones(5, dtype=np.float32)
b = np.arange(5, dtype=np.float32)
np.add(a, b, out=b)
np.multiply(a, -0.5, out=a)
np.multiply(a, b, out=a)

array([1., 2., 3., 4., 5.], dtype=float32)

array([-0.5, -0.5, -0.5, -0.5, -0.5], dtype=float32)

array([-0.5, -1. , -1.5, -2. , -2.5], dtype=float32)

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)

In [57]:
r = np.random.uniform(-10, 10, size=(5))
r
r.astype(np.int32)
np.floor(r)
np.ceil(r)
np.round(r)
np.trunc(r)

array([-6.54926856,  1.43916708, -3.18557711, -4.17286026, -3.3253776 ])

array([-6,  1, -3, -4, -3], dtype=int32)

array([-7.,  1., -4., -5., -4.])

array([-6.,  2., -3., -4., -3.])

array([-7.,  1., -3., -4., -3.])

array([-6.,  1., -3., -4., -3.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [58]:
np.arange(25).reshape([5, 5]) % 5

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [59]:
def gen():
    for i in range(10):
        yield i*i
        
np.array(list(gen()), dtype=np.int32)
np.fromiter(gen(), dtype=np.int32)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [60]:
np.linspace(0, 1, 10, endpoint=False)[1:]

array([0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [61]:
a = np.random.rand(10)
a
np.sort(a)

array([0.46063618, 0.73725162, 0.85446597, 0.7159211 , 0.85820959,
       0.73872132, 0.22509164, 0.57397206, 0.32659851, 0.61516688])

array([0.22509164, 0.32659851, 0.46063618, 0.57397206, 0.61516688,
       0.7159211 , 0.73725162, 0.73872132, 0.85446597, 0.85820959])

#### 41. How to sum a small array faster than np.sum? (★★☆)

In [62]:
a = np.arange(1000)

%timeit np.sum(a)

%timeit np.add.reduce(a, 0)

3.19 µs ± 286 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
1.78 µs ± 75.5 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [63]:
a = np.arange(5)
b = np.arange(5)
np.equal(a, b)
np.array_equal(a, b)
np.allclose(a, b)

array([ True,  True,  True,  True,  True])

True

True

#### 43. Make an array immutable (read-only) (★★☆)

In [64]:
a = np.array([1, 2, 3])
a[0] = 2
a

a.flags.writeable=False
a.setflags(write=False)
try:
  a[0] = 3
except BaseException as e:
  print('fail:', e)

array([2, 2, 3])

fail: assignment destination is read-only


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [65]:
c = np.random.randn(10, 2)
c

r = np.sqrt(np.sum(c**2, axis=1))
alpha = np.arctan2(c[:, 1], c[:, 0])

r
alpha

array([[-0.44678538, -0.53070503],
       [-0.39597001, -1.20614915],
       [ 0.17006977,  0.45009578],
       [-1.14223823, -0.96651925],
       [-1.36886774, -1.03013572],
       [-0.6446488 ,  0.57296518],
       [ 0.03338134,  0.72969428],
       [-0.00625212, -0.36047167],
       [ 1.57174651,  0.99568803],
       [-2.41411992,  2.02970725]])

array([0.69373266, 1.26948337, 0.48115479, 1.49628462, 1.71317789,
       0.86247386, 0.73045743, 0.36052589, 1.8605864 , 3.15399533])

array([-2.27055234, -1.88800351,  1.20952727, -2.43933063, -2.4964642 ,
        2.41499882,  1.52508118, -1.58813886,  0.56468226,  2.44248454])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [66]:
r = np.random.randn(10)
r
r[np.argmax(r)] = 0
r

array([ 1.02521353, -0.65666933,  1.08643358, -1.14777535, -0.43748195,
        0.23676167, -0.13322606, -0.10801871, -0.32917644,  1.35363942])

array([ 1.02521353, -0.65666933,  1.08643358, -1.14777535, -0.43748195,
        0.23676167, -0.13322606, -0.10801871, -0.32917644,  0.        ])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)

In [67]:
x = y = np.linspace(0, 1, 10)
a, b = np.meshgrid(x, y)
a
b

array([[0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
        0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ],
       [0.        , 0.11111111, 0.2222222

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111,
        0.11111111, 0.11111111, 0.11111111, 0.11111111, 0.11111111],
       [0.22222222, 0.22222222, 0.22222222, 0.22222222, 0.22222222,
        0.22222222, 0.22222222, 0.22222222, 0.22222222, 0.22222222],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333,
        0.33333333, 0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444,
        0.44444444, 0.44444444, 0.44444444, 0.44444444, 0.44444444],
       [0.55555556, 0.55555556, 0.55555556, 0.55555556, 0.55555556,
        0.55555556, 0.55555556, 0.55555556, 0.55555556, 0.55555556],
       [0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667,
        0.66666667, 0.66666667, 0.66666667, 0.66666667, 0.66666667],
       [0.77777778, 0.77777778, 0.7777777

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [68]:
x = np.arange(10) + 10
y = np.arange(10)
c = np.expand_dims(x, 1) - np.expand_dims(y, 0)
c

np.subtract.outer(x, y)

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2],
       [12, 11, 10,  9,  8,  7,  6,  5,  4,  3],
       [13, 12, 11, 10,  9,  8,  7,  6,  5,  4],
       [14, 13, 12, 11, 10,  9,  8,  7,  6,  5],
       [15, 14, 13, 12, 11, 10,  9,  8,  7,  6],
       [16, 15, 14, 13, 12, 11, 10,  9,  8,  7],
       [17, 16, 15, 14, 13, 12, 11, 10,  9,  8],
       [18, 17, 16, 15, 14, 13, 12, 11, 10,  9],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

array([[10,  9,  8,  7,  6,  5,  4,  3,  2,  1],
       [11, 10,  9,  8,  7,  6,  5,  4,  3,  2],
       [12, 11, 10,  9,  8,  7,  6,  5,  4,  3],
       [13, 12, 11, 10,  9,  8,  7,  6,  5,  4],
       [14, 13, 12, 11, 10,  9,  8,  7,  6,  5],
       [15, 14, 13, 12, 11, 10,  9,  8,  7,  6],
       [16, 15, 14, 13, 12, 11, 10,  9,  8,  7],
       [17, 16, 15, 14, 13, 12, 11, 10,  9,  8],
       [18, 17, 16, 15, 14, 13, 12, 11, 10,  9],
       [19, 18, 17, 16, 15, 14, 13, 12, 11, 10]])

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

In [69]:
np.iinfo(np.int8)
np.iinfo(np.int16)
np.iinfo(np.int32)

iinfo(min=-128, max=127, dtype=int8)

iinfo(min=-32768, max=32767, dtype=int16)

iinfo(min=-2147483648, max=2147483647, dtype=int32)

#### 49. How to print all the values of an array? (★★☆)

In [70]:
a = np.arange(5)
print(a)

[0 1 2 3 4]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [71]:
a
b = 1.8
a[np.argmin(np.abs(a - b))]

array([0, 1, 2, 3, 4])

2

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [72]:
a = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
a

array([((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.)),
       ((0., 0.), (0., 0., 0.)), ((0., 0.), (0., 0., 0.))],
      dtype=[('position', [('x', '<f8'), ('y', '<f8')]), ('color', [('r', '<f8'), ('g', '<f8'), ('b', '<f8')])])

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

In [73]:
a = np.arange(10).reshape((-1, 2))
d = np.expand_dims(a, 1) - np.expand_dims(a, 0)
a
np.sqrt(np.sum(d**2, axis=2))

x, y = np.atleast_2d(a[:,0], a[:,1])
np.sqrt((x-x.T)**2 + (y-y.T)**2)

import scipy.spatial
scipy.spatial.distance.cdist(a, a)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

array([[ 0.        ,  2.82842712,  5.65685425,  8.48528137, 11.3137085 ],
       [ 2.82842712,  0.        ,  2.82842712,  5.65685425,  8.48528137],
       [ 5.65685425,  2.82842712,  0.        ,  2.82842712,  5.65685425],
       [ 8.48528137,  5.65685425,  2.82842712,  0.        ,  2.82842712],
       [11.3137085 ,  8.48528137,  5.65685425,  2.82842712,  0.        ]])

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [74]:
x = np.random.rand(5, 5) * 5
x
x.astype(np.int, copy=False)

array([[1.84188234, 2.50096759, 0.14740137, 1.62351915, 3.78599145],
       [0.95771875, 1.99177937, 3.94509351, 4.5082855 , 1.81660978],
       [1.51057778, 1.26605245, 4.1732223 , 1.19030904, 2.39911136],
       [0.94934738, 4.00956201, 0.65058599, 3.94625098, 4.00065293],
       [2.54056686, 0.96258273, 4.17693089, 0.73260557, 4.46197104]])

array([[1, 2, 0, 1, 3],
       [0, 1, 3, 4, 1],
       [1, 1, 4, 1, 2],
       [0, 4, 0, 3, 4],
       [2, 0, 4, 0, 4]])

#### 54. How to read the following file? (★★☆)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [75]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
np.genfromtxt(s, delimiter=",")

array([[ 1.,  2.,  3.,  4.,  5.],
       [ 6., nan, nan,  7.,  8.],
       [nan, nan,  9., 10., 11.]])

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [76]:
x = np.random.randn(2, 2)
for i, val in np.ndenumerate(x):
    print(i, val)
for i in np.ndindex(x.shape):
    print(i)

(0, 0) -0.7386882748641992
(0, 1) 0.43176463608679067
(1, 0) -0.6098140044773539
(1, 1) 0.6107578380470177
(0, 0)
(0, 1)
(1, 0)
(1, 1)


#### 56. Generate a generic 2D Gaussian-like array (★★☆)

In [77]:
x, y = np.meshgrid(np.linspace(-1,1,4), np.linspace(-1,1,4))
d = np.sqrt(x*x + y*y)
sigma, mu = 1.0, 0.0
np.exp(-((d-mu)**2 / (2.0*sigma**2)))

array([[0.36787944, 0.57375342, 0.57375342, 0.36787944],
       [0.57375342, 0.89483932, 0.89483932, 0.57375342],
       [0.57375342, 0.89483932, 0.89483932, 0.57375342],
       [0.36787944, 0.57375342, 0.57375342, 0.36787944]])

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [78]:
a = np.zeros([5, 5])
v = np.arange(10) + 1
a.ravel()[np.random.choice(25, 10)] = v
a

array([[ 0.,  6.,  0.,  0.,  7.],
       [ 0.,  0.,  9.,  0.,  0.],
       [ 5.,  0.,  4.,  0.,  0.],
       [ 0.,  0.,  0.,  3.,  1.],
       [10.,  0.,  0.,  0.,  0.]])

#### 58. Subtract the mean of each row of a matrix (★★☆)

In [79]:
a = np.random.randn(4, 4)
a
a.mean(axis=1)
a.mean(axis=1, keepdims=True)

array([[-1.91742205, -0.96336006, -1.16549866,  0.60477088],
       [-1.05395592, -1.3162861 ,  0.84423458, -1.27812836],
       [-0.0155456 , -0.44990489,  1.09548844, -0.38596692],
       [ 0.70411048,  0.3069265 ,  0.59592952,  0.14728556]])

array([-0.86037747, -0.70103395,  0.06101776,  0.43856301])

array([[-0.86037747],
       [-0.70103395],
       [ 0.06101776],
       [ 0.43856301]])

#### 59. How to sort an array by the nth column? (★★☆)

In [83]:
a = np.random.randn(5, 5)
#np.sort(a, axis=1)
a[a[:,2].argsort()]

array([[ 0.84039862, -0.47540586, -1.73448006,  2.2331729 ,  0.52976641],
       [-0.4546214 , -0.12401622, -0.68141938, -0.40101347,  0.90871497],
       [-1.00309899, -1.89046703, -0.19503315,  1.51703536, -0.66915752],
       [ 0.74062966, -0.91814442,  0.52806282, -0.4300738 , -2.24074761],
       [ 0.93695204, -1.5133903 ,  0.94506771, -1.83150919,  2.34274914]])

#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [95]:
b = np.random.randn(3, 6)
b[:, 1] = np.nan
np.logical_and.reduce(np.isnan(b), axis=0)

array([False,  True, False, False, False, False])

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)